<?php

$wdwt_allowed_for_footer = array(
	'address' => array(),
	'a' => array(
		'href' => true,
		'rel' => true,
		'rev' => true,
		'name' => true,
		'target' => true,
	),
	'abbr' => array(),
	'area' => array(
		'alt' => true,
		'coords' => true,
		'href' => true,
		'nohref' => true,
		'shape' => true,
		'target' => true,
	),
	'audio' => array(
		'autoplay' => true,
		'controls' => true,
		'loop' => true,
		'muted' => true,
		'preload' => true,
		'src' => true,
	),
	'b' => array(),
	'big' => array(),
	'blockquote' => array(
		'cite' => true,
		'lang' => true,
		'xml:lang' => true,
	),
	'br' => array(),
	'button' => array(
		'disabled' => true,
		'name' => true,
		'type' => true,
		'value' => true,
	),
	'caption' => array(
		'align' => true,
	),
	'cite' => array(
		'dir' => true,
		'lang' => true,
	),
	'code' => array(),
	'col' => array(
		'align' => true,
		'char' => true,
		'charoff' => true,
		'span' => true,
		'dir' => true,
		'valign' => true,
		'width' => true,
	),
	'colgroup' => array(
		'align' => true,
		'char' => true,
		'charoff' => true,
		'span' => true,
		'valign' => true,
		'width' => true,
	),
	'del' => array(
		'datetime' => true,
	),
	'dd' => array(),
	'dfn' => array(),
	'details' => array(
		'align' => true,
		'dir' => true,
		'lang' => true,
		'open' => true,
		'xml:lang' => true,
	),
	'div' => array(
		'align' => true,
		'dir' => true,
		'lang' => true,
		'xml:lang' => true,
	),
	'dl' => array(),
	'dt' => array(),
	'em' => array(),
	'fieldset' => array(),
	'figure' => array(
		'align' => true,
		'dir' => true,
		'lang' => true,
		'xml:lang' => true,
	),
	'figcaption' => array(
		'align' => true,
		'dir' => true,
		'lang' => true,
		'xml:lang' => true,
	),
	'font' => array(
		'color' => true,
		'face' => true,
		'size' => true,
	),
	'form' => array(
		'action' => true,
		'accept' => true,
		'accept-charset' => true,
		'enctype' => true,
		'method' => true,
		'name' => true,
		'target' => true,
	),
	'h1' => array(
		'align' => true,
	),
	'h2' => array(
		'align' => true,
	),
	'h3' => array(
		'align' => true,
	),
	'h4' => array(
		'align' => true,
	),
	'h5' => array(
		'align' => true,
	),
	'h6' => array(
		'align' => true,
	),
	'hgroup' => array(
		'align' => true,
		'dir' => true,
		'lang' => true,
		'xml:lang' => true,
	),
	'hr' => array(
		'align' => true,
		'noshade' => true,
		'size' => true,
		'width' => true,
	),
	'i' => array(),
	'img' => array(
		'alt' => true,
		'align' => true,
		'border' => true,
		'height' => true,
		'hspace' => true,
		'longdesc' => true,
		'vspace' => true,
		'src' => true,
		'usemap' => true,
		'width' => true,
	),
	'ins' => array(
		'datetime' => true,
		'cite' => true,
	),
	'kbd' => array(),
	'label' => array(
		'for' => true,
	),
	'legend' => array(
		'align' => true,
	),
	'li' => array(
		'align' => true,
		'value' => true,
	),
	'map' => array(
		'name' => true,
	),
	'mark' => array(),
	'menu' => array(
		'type' => true,
	),
	'nav' => array(
		'align' => true,
		'dir' => true,
		'lang' => true,
		'xml:lang' => true,
	),
	'p' => array(
		'align' => true,
		'dir' => true,
		'lang' => true,
		'xml:lang' => true,
	),
	'pre' => array(
		'width' => true,
	),
	'q' => array(
		'cite' => true,
	),
	's' => array(),
	'samp' => array(),
	'span' => array(
		'dir' => true,
		'align' => true,
		'lang' => true,
		'xml:lang' => true,
	),
	'small' => array(),
	'strike' => array(),
	'strong' => array(),
	'sub' => array(),
	'summary' => array(
		'align' => true,
		'dir' => true,
		'lang' => true,
		'xml:lang' => true,
	),
	'sup' => array(),
	'table' => array(
		'align' => true,
		'bgcolor' => true,
		'border' => true,
		'cellpadding' => true,
		'cellspacing' => true,
		'dir' => true,
		'rules' => true,
		'summary' => true,
		'width' => true,
	),
	'tbody' => array(
		'align' => true,
		'char' => true,
		'charoff' => true,
		'valign' => true,
	),
	'td' => array(
		'abbr' => true,
		'align' => true,
		'axis' => true,
		'bgcolor' => true,
		'char' => true,
		'charoff' => true,
		'colspan' => true,
		'dir' => true,
		'headers' => true,
		'height' => true,
		'nowrap' => true,
		'rowspan' => true,
		'scope' => true,
		'valign' => true,
		'width' => true,
	),
	'textarea' => array(
		'cols' => true,
		'rows' => true,
		'disabled' => true,
		'name' => true,
		'readonly' => true,
	),
	'tfoot' => array(
		'align' => true,
		'char' => true,
		'charoff' => true,
		'valign' => true,
	),
	'th' => array(
		'abbr' => true,
		'align' => true,
		'axis' => true,
		'bgcolor' => true,
		'char' => true,
		'charoff' => true,
		'colspan' => true,
		'headers' => true,
		'height' => true,
		'nowrap' => true,
		'rowspan' => true,
		'scope' => true,
		'valign' => true,
		'width' => true,
	),
	'thead' => array(
		'align' => true,
		'char' => true,
		'charoff' => true,
		'valign' => true,
	),
	'tr' => array(
		'align' => true,
		'bgcolor' => true,
		'char' => true,
		'charoff' => true,
		'valign' => true,
	),
	'track' => array(
		'default' => true,
		'kind' => true,
		'label' => true,
		'src' => true,
		'srclang' => true,
	),
	'tt' => array(),
	'u' => array(),
	'ul' => array(
		'type' => true,
	),
	'ol' => array(
		'start' => true,
		'type' => true,
	),
	'var' => array(),
	'video' => array(
		'autoplay' => true,
		'controls' => true,
		'height' => true,
		'loop' => true,
		'muted' => true,
		'poster' => true,
		'preload' => true,
		'src' => true,
		'width' => true,
	),
);


$wdwt_allowed_for_slider_desc = array(
	'a' => array(
		'href' => true,
		'title' => true,
	),
	'abbr' => array(
		'title' => true,
	),
	'acronym' => array(
		'title' => true,
	),
	'b' => array(),
	'blockquote' => array(
		'cite' => true,
	),
	'cite' => array(),
	'code' => array(),
	'del' => array(
		'datetime' => true,
	),
	'em' => array(),
	'h1' => array(
		'align' => true,
	),
	'h2' => array(
		'align' => true,
	),
	'h3' => array(
		'align' => true,
	),
	'h4' => array(
		'align' => true,
	),
	'h5' => array(
		'align' => true,
	),
	'h6' => array(
		'align' => true,
	),
	'hr' => array(
		'align' => true,
		'noshade' => true,
		'size' => true,
		'width' => true,
	),
	'i' => array(),
	'q' => array(
		'cite' => true,
	),
	's' => array(),
	'strike' => array(),
	'strong' => array(),
);

$wdwt_allowed_for_custom_head = array(
	'meta' => array(
		'charset' => true,
		'content' => true,
		'http-equiv' => true,
		'name' => true,
		'scheme' => true,
	),
	'script' => array(
		'charset' => true,
		'defer' => true,
		'src' => true,
		'type' => true,
		'xml:space' => true,
	),
	'style' => array(
		'media' => true,
		'scoped' => true,
		'type' => true,
	),
	'link' => array(
	    'charset' => true,
	    'href' => true,
	    'rel' => true,
	    'type' => true,
	    'target' => true,
	    'title' => true,
	),
);


?>